from operator import index

from utils import get_now
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import FOAF, RDF, OWL, RDFS

class HumanFix:

    def __init__(
        self,
        schema,
        onto,
        prefix,
        namespace,
        components_root,
        errors,
        modules
    ):
        self.log = []
        self.schema = schema,
        self.onto = onto,
        self.prefix = prefix,
        self.namespace = namespace,
        self.components_root = components_root,
        self.errors = errors
        self.modules = modules
        self.user = User()

    def set_user_info(self):
        self.user.set_name()
        self.user.set_id()
        self.user.set_role()
        self.user.build_user_triples(
            self.prefix,
            self.namespace
        )
        self.onto = self.onto + self.user.g
        self.log.append(f"Assigned manual user: {self.user.name}")

    def concepts_to_add_output(self, path):
        if self.concepts_to_add:
            with (path / "Concepts_to_add_manually.txt").open("w", encoding="utf-8") as f:
                for c in self.concepts_to_add:
                    f.write(c + "\n")
            print("Missing concepts recorded successfully")
        else:
            print("No concepts to manually add")

    def fix_rubrex(self, errors):
        print("""

        ======== These errors were created by the RuBREx Module ========

        """)
        # TODO: Implement embedded RDF injection tool
        print(f"{len(errors)} raised by the RuBREx module")

        self.concepts_to_add = []

        for e in errors:
            print(f"""
            Error {errors.index(e)} of {len(errors)}
            ----------------------------------------
            error: {e[1]}
            """)
            user_ans = input("Should this concept be represented in the ontology? (y/N)")
            if user_ans == "N":
                self.log.append(f"Rejected representing {e[1]}")
                continue
            else:
                self.log.append(f"Assigned {e[1]} to be manually represented")
                self.concepts_to_add.append(e[1])


    def process_context(self, context):
        context_list = []
        reject_relations = [
            "http://www.w3.org/2000/01/rdf-schema#label",
            f"{self.prefix}:generatedBy",
            f"{self.prefix}:hasXSDSource"
        ]
        for l in context.keys():
            for r in context[l]:
                if r[0] in reject_relations:
                    continue
                triple = [l, r[0], r[1]]
                context_list.append(triple)
        print(context_list)
        return context_list


    def replace_relation(self, original, new):
        query = f"""
        PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX owl:  <http://www.w3.org/2002/07/owl#>

        SELECT ?s ?p ?o WHERE{{
            ?s ?p ?o
            FITLER(
                ?s = <{self.namespace}{original}> ||
                ?p = <{self.namespace}{original}> ||
                ?o = <{self.namespace}{original}>
            )
        }}
        """
        qres = self.onto.query(query)

        for r in qres:

            if r.p == str(RDFS.label):
                n_sub = URIRef(f"{self.namespace}{new}")
                n_obj = Literal(new)
                self.onto.remove((r.s, r.p, r.o))
                self.onto.add((n_sub, r.p, n_obj))
            elif r.s == f"{self.namespace}{original}":
                n_sub = URIRef(f"{self.namespace}{new}")
                self.onto.remove((r.s, r.p, r.o))
                self.onto.add((n_sub, r.p, r.o))
            elif r.p == f"{self.namespace}{original}":
                n_pred = URIRef(f"{self.namespace}{new}")
                self.onto.remove((r.s, r.p, r.o))
                self.onto.add((r.s, n_pred, r.o))
            elif r.o == f"{self.namespace}{original}":
                n_obj = URIRef(f"{self.namespace}{new}")
                self.onto.remove((r.s, r.p, r.o))
                self.onto.add((r.s, r.p, n_obj))

        s = URIRef(f"{self.namespace}{new}")
        p = URIRef(f"{self.namespace}editedBy")
        o = Literal(f"{self.user.id} @ {get_now()}")
        self.onto.add([s, p, o])
        self.log.append(f"Relationship {original} updated to {new}.")

    def fix_llm_ref(self, errors):
        # TODO: Deal with errors generated by LLM Refinement Loop
        print("""

        ======== These errors were created by the LLM Refinement Loop Module ========

        """)
        # NOTE: Error format
        # self.errors.append([rel, rel_info, response[1]])
        print(f"{len(errors)} raised by the LLM Refinement Loop module")

        for e in errors:
            print(f"""
            Error {errors.index(e)} of {len(errors)}
            ----------------------------------------
            Relationship: {e[1]}
            Triples using property:""")
            info = self.process_context(e[1])
            for r in info:
                print(r)
            print(f"""
            Rejected Labels: {e[2]}

            """)
            user_lab = input("Please enter an accurate label for this relationship")
            self.replace_relation(e[1], user_lab)


    def fix_errors(self):
        modules = [
            module.strip()
            for module in self.modules.split(",")
            if module.strip()
        ]
        # NOTE: Additional functions required for additional modules
        for r in self.errors:
            mod = modules[self.errors[r].index()]
            if mod == "RuBREx":
                self.fix_rubrex(r)
            elif mod == "LLM_Refinement_Loop":
                self.fix_llm_ref(r)


class User:

    def __init__(self):
        pass

    def set_name(self):
        name = ""
        while not name:
            name = input(
                "Please enter your name: "
            )
            if not name:
                print("Please enter a valid name")
        self.name = name

    def set_id(self):
        id = ""
        while not id:
            id = input(
                "Please enter your ID: "
            )
            if not id:
                print("Please enter a valid ID")
        self.id = id

    def set_role(self):
        role = ""
        while not role:
            role = input(
                "Please enter your role if you have one: "
            )
            if not role:
                role = "N/A"
        self.role = role

    def build_user_triples(self, namespace, prefix):
        self.g = Graph()
        self.g.bind("foaf", FOAF)
        self.g.bind("owl", OWL)
        self.g.bind("rdf", RDF)
        self.g.bind(prefix, namespace)

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            RDF.type,
            OWL.Class
        ))

        self.g.add((
            URIRef(f"{namespace}{self.role}"),
            RDF.type,
            OWL.Class
        ))

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            FOAF.name,
            Literal(self.name)
        ))

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            URIRef(f"{namespace}hasReviewerId"),
            Literal(int(self.id))
        ))

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            URIRef(f"{namespace}hasReviewerRole"),
            URIRef(f"{namespace}{self.role}")
        ))

