from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import FOAF, RDF, OWL

class HumanFix:

    def __init__(
        self,
        schema,
        onto,
        prefix,
        namespace,
        components_root,
        errors,
        modules
    ):
        self.schema = schema,
        self.onto = onto,
        self.prefix = prefix,
        self.namespace = namespace,
        self.components_root = components_root,
        self.errors = errors
        self.modules = modules
        self.user = User()

    def set_user_info(self):
        self.user.set_name()
        self.user.set_id()
        self.user.set_role()
        self.user.build_user_triples(
            self.prefix,
            self.namespace
        )
        self.onto = self.onto + self.user.g

    def fix_rubrex(self, errors):
        # TODO: Deal with errors generated by RuBREx
        print("""

        ======== These errors were created by the RuBREx Module ========

        """)

    def fix_llm_ref(self, errors):
        # TODO: Deal with errors generated by LLM Refinement Loop
        print("""

        ======== These errors were created by the LLM Refinement Loop Module ========

        """)

    def fix_errors(self):
        modules = [
            module.strip()
            for module in self.modules.split(",")
            if module.strip()
        ]
        # NOTE: Additional functions required for additional modules
        for r in self.errors:
            mod = modules[self.errors[r].index()]
            if mod == "RuBREx":
                self.fix_rubrex(r)
            elif mod == "LLM_Refinement_Loop":
                self.fix_llm_ref(r)


class User:

    def __init__(self):
        pass

    def set_name(self):
        name = ""
        while not name:
            name = input(
                "Please enter your name: "
            )
            if not name:
                print("Please enter a valid name")
        self.name = name

    def set_id(self):
        id = ""
        while not id:
            id = input(
                "Please enter your ID: "
            )
            if not id:
                print("Please enter a valid ID")
        self.id = id

    def set_role(self):
        role = ""
        while not role:
            role = input(
                "Please enter your role if you have one: "
            )
            if not role:
                role = "N/A"
        self.role = role

    def build_user_triples(self, namespace, prefix):
        self.g = Graph()
        self.g.bind("foaf", FOAF)
        self.g.bind("owl", OWL)
        self.g.bind("rdf", RDF)
        self.g.bind(prefix, namespace)

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            RDF.type,
            OWL.Class
        ))

        self.g.add((
            URIRef(f"{namespace}{self.role}"),
            RDF.type,
            OWL.Class
        ))

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            FOAF.name,
            Literal(self.name)
        ))

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            URIRef(f"{namespace}hasReviewerId"),
            Literal(int(self.id))
        ))

        self.g.add((
            URIRef(f"{namespace}{self.id}"),
            URIRef(f"{namespace}hasReviewerRole"),
            URIRef(f"{namespace}{self.role}")
        ))

